// Cambridge IELTS 20 — Extra Passages (auto-appended to PASSAGES)
const CAM20_EXTRA = [

// ══════════════════════════════════════════════════════════════════════════
// TEST 1 — PASSAGE 3
// ══════════════════════════════════════════════════════════════════════════
{
  id: 'cam20-t1-p3',
  title: 'How stress affects our judgement',
  topic: 'Psychology & Neuroscience',
  band: '7.0 – 8.0',
  difficulty: 'Advanced',
  source: '📗 Cambridge IELTS 20 — Test 1, Passage 3',
  wordCount: 850,
  estimatedTime: 20,
  text: `<strong>Some of the most important decisions of our lives occur while we're feeling stressed and anxious.</strong> From medical decisions to financial and professional ones, we are all sometimes required to weigh up information under stressful conditions. But do we become better or worse at processing and using information under such circumstances?

My colleague and I, both neuroscientists, wanted to investigate how the mind operates under stress, so we visited some local fire stations. Firefighters' workdays vary quite a bit. Some are pretty relaxed; they'll spend their time washing the truck, cleaning equipment, cooking meals and reading. Other days can be hectic, with numerous life-threatening incidents to attend to; they'll enter burning homes to rescue trapped residents, and assist with medical emergencies. These ups and downs presented the perfect setting for an experiment on how people's ability to use information changes when they feel under pressure.

We found that perceived threat acted as a trigger for a stress reaction that made the task of processing information easier for the firefighters – but only as long as it conveyed bad news. This is how we arrived at these results. We asked the firefighters to estimate their likelihood of experiencing 40 different adverse events in their life, such as being involved in an accident or becoming a victim of card fraud. We then gave them either good news (that their likelihood of experiencing these events was lower than they'd thought) or bad news (that it was higher) and asked them to provide new estimates. People are normally quite optimistic – they will ignore bad news and embrace the good. This is what happened when the firefighters were relaxed; but when they were under stress, a different pattern emerged. Under these conditions, they became hyper-vigilant to bad news, even when it had nothing to do with their job (such as learning that the likelihood of card fraud was higher than they'd thought), and altered their beliefs in response. In contrast, stress didn't change how they responded to good news.

Back in our lab, we observed the same pattern in students who were told they had to give a surprise public speech, which would be judged by a panel, recorded and posted online. Sure enough, their cortisol levels spiked, their heart rates went up and they suddenly became better at processing unrelated, yet alarming, information about rates of disease and violence.

When we experience stressful events, a physiological change is triggered that causes us to take in warnings and focus on what might go wrong. Brain imaging reveals that this 'switch' is related to a sudden boost in a neural signal important for learning, specifically in response to unexpected warning signs, such as faces expressing fear. Such neural engineering could have helped prehistoric humans to survive. When our ancestors found themselves surrounded by hungry animals, they would have benefited from an increased ability to learn about hazards. In a safe environment, however, it would have been wasteful to be on high alert constantly. So, a neural switch that automatically increases or decreases our ability to process warnings in response to changes in our environment could have been useful. In fact, people with clinical depression and anxiety seem unable to switch away from a state in which they absorb all the negative messages around them.

It is also important to realise that stress travels rapidly from one person to the next. If a co-worker is stressed, we are more likely to tense up and feel stressed ourselves. We don't even need to be in the same room with someone for their emotions to influence our behaviour.

Studies show that if we observe positive feeds on social media, such as images of a pink sunset, we are more likely to post uplifting messages ourselves. If we observe negative posts, such as complaints about a long queue at the coffee shop, we will in turn create more negative posts.

In some ways, many of us now live as if we are in danger, constantly ready to tackle demanding emails and text messages, and respond to news alerts and comments on social media. Repeatedly checking your phone, according to a survey conducted by the American Psychological Association, is related to stress. In other words, a pre-programmed physiological reaction, which evolution has equipped us with to help us avoid famished predators, is now being triggered by an online post.

The fact that stress increases the likelihood that we will focus more on alarming messages, together with the fact that it spreads extremely rapidly, can create collective fear that is not always justified. After a stressful public event, such as a natural disaster or major financial crash, there is often a wave of alarming information in traditional and social media, which individuals become very aware of. But that has the effect of exaggerating existing danger. And so, a reliable pattern emerges – stress is triggered, spreading from one person to the next, which temporarily enhances the likelihood that people will take in negative reports, which increases stress further. As a result, trips are cancelled, even if the disaster took place across the globe; stocks are sold, even when holding on is the best thing to do.

The good news, however, is that positive emotions, such as hope, are contagious too, and are powerful in inducing people to act to find solutions. Being aware of the close relationship between people's emotional state and how they process information can help us frame our messages more effectively and become conscientious agents of change.`,
  questions: [
    { id: 1, type: 'mc', question: 'In the first paragraph, the writer introduces the topic by', options: ['A. defining some commonly used terms.', 'B. questioning a widely held assumption.', 'C. mentioning a challenge faced by everyone.', 'D. specifying a situation which makes us most anxious.'], answer: 'C', hints: ['Đoạn 1 nêu vấn đề gì mà ai cũng gặp?', 'Tìm cụm "we are all sometimes required…"', 'Đó là thách thức chung hay giả định?'], explanation: 'C — Đoạn 1: <em>"we are all sometimes required to weigh up information under stressful conditions"</em> — thách thức chung.' },
    { id: 2, type: 'mc', question: 'What point does the writer make about firefighters in the second paragraph?', options: ['A. The regular changes of stress levels make them ideal study subjects.', 'B. The strategies they use to handle stress are of particular interest.', 'C. The stressful nature of their job is typical of many professions.', 'D. Their personalities make them especially well-suited to stress.'], answer: 'A', hints: ['Tại sao chọn lính cứu hỏa?', 'Tìm "ups and downs presented the perfect setting"', 'Sự thay đổi mức stress giúp gì cho thí nghiệm?'], explanation: 'A — <em>"These ups and downs presented the perfect setting for an experiment"</em>.' },
    { id: 3, type: 'mc', question: 'What is the writer doing in the fourth paragraph?', options: ['A. explaining their findings', 'B. justifying their approach', 'C. setting out their objectives', 'D. describing their methodology'], answer: 'A', hints: ['Đoạn 4 bắt đầu bằng "We found that…"', 'Đó là kết quả hay phương pháp?', 'Tìm "results" trong đoạn này.'], explanation: 'A — Đoạn 4 trình bày kết quả: <em>"We found that perceived threat acted as a trigger…"</em>.' },
    { id: 4, type: 'mc', question: 'In the seventh paragraph, the writer describes a brain mechanism which', options: ['A. enables people to respond more quickly to stress.', 'B. results in increased ability to control anxiety.', 'C. produces heightened sensitivity to indications of external threats.', 'D. is activated when there is a need to communicate danger.'], answer: 'C', hints: ['Đoạn 7 nói về "neural switch" làm gì?', 'Tìm "boost in a neural signal… warning signs"', 'Switch này tăng hay giảm khả năng nhận biết mối nguy?'], explanation: 'C — <em>"a sudden boost in a neural signal… in response to unexpected warning signs"</em>.' },
    { id: 5, type: 'mc', question: 'Q31: At times when they were relaxed, the firefighters usually ___', options: ['A. made them feel optimistic.', 'B. took relatively little notice of bad news.', 'C. responded to negative and positive information in the same way.', 'D. were feeling under stress.'], answer: 'B', hints: ['Khi thư giãn, lính cứu hỏa phản ứng thế nào?', 'Tìm "People are normally quite optimistic – they will ignore bad news"', 'Họ bỏ qua tin xấu khi thư giãn?'], explanation: 'B — <em>"People are normally quite optimistic – they will ignore bad news and embrace the good"</em>.' },
    { id: 6, type: 'mc', question: 'Q32: When stressed, the firefighters ___', options: ['A. made them feel optimistic.', 'B. took relatively little notice of bad news.', 'C. responded to negative and positive info the same way.', 'D. were feeling under stress.', 'E. put them in a stressful situation.', 'F. behaved similarly regardless of circumstances.', 'G. thought it more likely they would experience something bad.'], answer: 'G', hints: ['Khi stress, phản ứng với tin xấu thay đổi thế nào?', 'Tìm "hyper-vigilant to bad news… altered their beliefs"', 'Họ nghĩ khả năng gặp chuyện xấu cao hơn?'], explanation: 'G — Khi stress: <em>"they became hyper-vigilant to bad news… and altered their beliefs in response"</em>.' },
    { id: 7, type: 'mc', question: 'Q33: When told good news, the firefighters always ___', options: ['A. made them feel optimistic.', 'B. took relatively little notice of bad news.', 'C. responded to negative and positive info the same way.', 'D. were feeling under stress.', 'E. put them in a stressful situation.', 'F. behaved similarly regardless of circumstances.', 'G. thought it more likely they would experience something bad.'], answer: 'A', hints: ['Phản ứng với tin tốt có thay đổi theo stress không?', 'Tìm "stress didn\'t change how they responded to good news"', 'Tin tốt luôn khiến họ cảm thấy thế nào?'], explanation: 'A — <em>"stress didn\'t change how they responded to good news"</em> — tin tốt luôn khiến họ lạc quan.' },
    { id: 8, type: 'mc', question: 'Q34: The students\' cortisol levels were affected when the researchers ___', options: ['A. made them feel optimistic.', 'B. took relatively little notice of bad news.', 'C. responded the same way.', 'D. were feeling under stress.', 'E. put them in a stressful situation.', 'F. behaved similarly.', 'G. thought it more likely they would experience something bad.'], answer: 'E', hints: ['Điều gì khiến cortisol của sinh viên tăng?', 'Tìm "told they had to give a surprise public speech"', 'Đó là tình huống gây stress?'], explanation: 'E — <em>"students who were told they had to give a surprise public speech… their cortisol levels spiked"</em>.' },
    { id: 9, type: 'mc', question: 'Q35: Negative information was processed better when the subjects ___', options: ['A. made them feel optimistic.', 'B. took little notice of bad news.', 'C. responded the same way.', 'D. were feeling under stress.', 'E. put them in a stressful situation.', 'F. behaved similarly.', 'G. thought it more likely they would experience something bad.'], answer: 'D', hints: ['Khi nào thông tin tiêu cực được xử lý tốt hơn?', 'Kết luận chung của cả 2 thí nghiệm?', 'Stress giúp xử lý thông tin xấu tốt hơn?'], explanation: 'D — Cả hai thí nghiệm cho thấy thông tin xấu được xử lý tốt hơn <em>khi đối tượng đang stress</em>.' },
    { id: 10, type: 'tfng', question: 'Q36: The tone of content we post on social media tends to reflect the nature of posts in our feeds.', answer: 'TRUE', hints: ['Đoạn 9 nói gì về ảnh hưởng của social media?', 'Tìm "if we observe positive feeds… we are more likely to post uplifting messages"', 'Nội dung ta đăng có phản ánh nội dung ta xem không?'], explanation: 'TRUE — <em>"if we observe positive feeds… we are more likely to post uplifting messages… If we observe negative posts… we will create more negative posts"</em>.' },
    { id: 11, type: 'tfng', question: 'Q37: Phones have a greater impact on our stress levels than other electronic media devices.', answer: 'NOT GIVEN', hints: ['Bài đọc có so sánh điện thoại với thiết bị khác không?', 'Tìm đoạn về "checking your phone"', 'Có nói thiết bị nào gây stress HƠN không?'], explanation: 'NOT GIVEN — Bài nêu kiểm tra điện thoại liên quan đến stress, nhưng không so sánh với thiết bị khác.' },
    { id: 12, type: 'tfng', question: 'Q38: The more we read about a stressful public event, the less able we are to take the information in.', answer: 'FALSE', hints: ['Đoạn cuối nói gì về xử lý thông tin tiêu cực sau sự kiện stress?', 'Stress làm tăng hay giảm khả năng tiếp nhận tin xấu?', 'Tìm "enhances the likelihood that people will take in negative reports"'], explanation: 'FALSE — Ngược lại: stress <em>"temporarily enhances the likelihood that people will take in negative reports"</em>.' },
    { id: 13, type: 'tfng', question: 'Q39: Stress created by social media posts can lead us to take unnecessary precautions.', answer: 'TRUE', hints: ['Đoạn cuối đưa ví dụ gì về hành động do stress?', 'Tìm "trips are cancelled… stocks are sold"', 'Đó là biện pháp phòng ngừa cần thiết hay không cần thiết?'], explanation: 'TRUE — <em>"trips are cancelled, even if the disaster took place across the globe; stocks are sold, even when holding on is the best thing to do"</em>.' },
    { id: 14, type: 'tfng', question: 'Q40: The writer believes that__(positive emotion can motivate people to take constructive action).', answer: 'TRUE', hints: ['Đoạn cuối cùng nói gì về cảm xúc tích cực?', 'Tìm "positive emotions… are powerful in inducing people to act"', 'Hy vọng có thể thúc đẩy hành động tích cực?'], explanation: 'TRUE — <em>"positive emotions, such as hope, are contagious too, and are powerful in inducing people to act to find solutions"</em>.' },
  ]
},

];

// Merge into main PASSAGES array
PASSAGES.push(...CAM20_EXTRA);
