// Cambridge IELTS 20 — Test 2 Passages
const CAM20_T2 = [

// ══════════════════════════════════════════════════════════════════════════
// TEST 2 — PASSAGE 1: Manatees
// ══════════════════════════════════════════════════════════════════════════
{
  id: 'cam20-t2-p1',
  title: 'Manatees',
  topic: 'Nature & Biology',
  band: '6.0 – 7.0',
  difficulty: 'Intermediate',
  source: '📗 Cambridge IELTS 20 — Test 2, Passage 1',
  wordCount: 780,
  estimatedTime: 20,
  text: `<strong>Manatees, also known as sea cows, are aquatic mammals that belong to a group of animals called Sirenia.</strong> This group also contains dugongs. Dugongs and manatees look quite alike – they are similar in size, colour and shape, and both have flexible flippers for forelimbs. However, the manatee has a broad, rounded tail, whereas the dugong's is fluked, like that of a whale. There are three species of manatees: the West Indian manatee, the African manatee and the Amazonian manatee.

Unlike most mammals, manatees have only six bones in their neck – most others, including humans and giraffes, have seven. This short neck allows a manatee to move its head up and down, but not side to side. To see something on its left or its right, a manatee must turn its entire body, steering with its flippers. Manatees have pectoral flippers but no back limbs, only a tail for propulsion. They do have pelvic bones, however, a leftover from their evolution from a four-legged to a fully aquatic animal. Manatees share some visual similarities to elephants. Like elephants, manatees have thick, wrinkled skin. They also have some hairs covering their bodies which help them sense vibrations in the water around them.

Seagrasses and other marine plants make up most of a manatee's diet. Manatees spend about eight hours each day grazing and uprooting plants. They eat up to 15% of their weight in food each day. African manatees are omnivorous – studies have shown that molluscs and fish make up a small part of their diets. West Indian and Amazonian manatees are both herbivores.

Manatees' teeth are all molars – flat, rounded teeth for grinding food. Due to manatees' abrasive aquatic plant diet, these teeth get worn down and they eventually fall out, so they continually grow new teeth that get pushed forward to replace the ones they lose. Instead of having incisors to grasp their food, manatees have lips which function like a pair of hands to help tear food away from the seafloor.

Manatees are fully aquatic, but as mammals, they need to come up to the surface to breathe. When awake, they typically surface every two to four minutes, but they can hold their breath for much longer. Adult manatees sleep underwater for 10–12 hours a day, but they come up for air every 15–20 minutes. Active manatees need to breathe more frequently. It is thought that manatees use their muscular diaphragm and breathing to adjust their buoyancy. They may use diaphragm contractions to compress and store gas in folds in their large intestine to help them float.

The West Indian manatee reaches about 3.5 metres long and weighs on average around 500 kilograms. It moves between fresh water and salt water, taking advantage of coastal mangroves and coral reefs, rivers, lakes and inland lagoons. There are two subspecies of West Indian manatee: the Antillean manatee is found in waters from the Bahamas to Brazil, whereas the Florida manatee is found in US waters. In winter, the Florida manatee is typically restricted to Florida. When the ambient water temperature drops below 20°C, it takes refuge in naturally and artificially warmed water, such as at the warm-water outfalls from powerplants.

The African manatee is also about 3.5 metres long and found in the sea along the west coast of Africa, from Mauritania down to Angola. The species also makes use of rivers, with the mammals seen in landlocked countries such as Mali and Niger. The Amazonian manatee is the smallest species. It grows to about 2.5 metres long and 350 kilogrammes. Amazonian manatees favour calm, shallow waters that are above 23°C.

All three manatee species are endangered or at a heightened risk of extinction. The African manatee and Amazonian manatee are both listed as Vulnerable by the IUCN. It is estimated that 140,000 Amazonian manatees were killed between 1935 and 1954 for their meat, fat and skin. In more recent years, African manatee decline has been tied to incidental capture in fishing nets and hunting.

The two subspecies of West Indian manatee are listed as Endangered by the IUCN. Both are also expected to undergo a decline of 20% over the next 40 years. A review of almost 1,800 cases of entanglement in fishing nets and of plastic consumption among marine mammals in US waters from 2009 to 2020 found that at least 700 cases involved manatees. The chief cause of death in Florida manatees is boat strikes. However, laws in certain parts of Florida now limit boat speeds during winter, allowing slow-moving manatees more time to respond.`,
  questions: [
    { id: 1, type: 'short', question: 'Q1: Manatees look similar to dugongs, but with a differently shaped (1) ___________.', answer: 'tail', hints: ['So sánh manatee và dugong ở đoạn 1.', 'Tìm "However, the manatee has a broad, rounded…"', 'Bộ phận nào khác nhau?'], explanation: 'tail — <em>"the manatee has a broad, rounded <strong>tail</strong>, whereas the dugong\'s is fluked"</em>.' },
    { id: 2, type: 'short', question: 'Q2: Manatees need to use their (2) ___________ to help turn their bodies to look sideways.', answer: 'flippers', hints: ['Đoạn 2 nói về cách manatee quay đầu.', 'Tìm "steering with its…"', 'Manatee dùng gì để lái?'], explanation: 'flippers — <em>"a manatee must turn its entire body, steering with its <strong>flippers</strong>"</em>.' },
    { id: 3, type: 'short', question: 'Q3: Manatees sense vibrations in the water by means of (3) ___________ on their skin.', answer: 'hairs', hints: ['Đoạn 2, phần nói về da manatee.', 'Tìm "help them sense vibrations"', 'Cái gì trên da giúp cảm nhận rung động?'], explanation: 'hairs — <em>"They also have some <strong>hairs</strong> covering their bodies which help them sense vibrations"</em>.' },
    { id: 4, type: 'short', question: 'Q4: Manatees eat mainly aquatic vegetation, such as (4) ___________.', answer: 'seagrasses', hints: ['Đoạn 3, dòng đầu tiên.', 'Tìm "make up most of a manatee\'s diet"', 'Loại thực vật biển nào được nêu tên đầu tiên?'], explanation: 'seagrasses — <em>"<strong>Seagrasses</strong> and other marine plants make up most of a manatee\'s diet"</em>.' },
    { id: 5, type: 'short', question: 'Q5: Manatees grasp and pull up plants with their (5) ___________.', answer: 'lips', hints: ['Đoạn 4, phần nói về cách ăn.', 'Tìm "function like a pair of hands"', 'Bộ phận nào thay thế incisors?'], explanation: 'lips — <em>"manatees have <strong>lips</strong> which function like a pair of hands to help tear food away"</em>.' },
    { id: 6, type: 'short', question: 'Q6: Manatees may regulate the (6) ___________ of their bodies using muscles of diaphragm.', answer: 'buoyancy', hints: ['Đoạn 5, phần nói về hô hấp và nổi.', 'Tìm "adjust their…"', 'Manatee điều chỉnh gì bằng cơ hoành?'], explanation: 'buoyancy — <em>"manatees use their muscular diaphragm and breathing to adjust their <strong>buoyancy</strong>"</em>.' },
    { id: 7, type: 'tfng', question: 'Q7: West Indian manatees can be found in a variety of different aquatic habitats.', answer: 'TRUE', hints: ['Đoạn 6 liệt kê nơi sống của West Indian manatee.', 'Tìm "coastal mangroves and coral reefs, rivers, lakes…"', 'Đó là nhiều loại môi trường khác nhau?'], explanation: 'TRUE — <em>"It moves between fresh water and salt water, taking advantage of coastal mangroves and coral reefs, rivers, lakes and inland lagoons"</em>.' },
    { id: 8, type: 'tfng', question: 'Q8: The Florida manatee lives in warmer waters than the Antillean manatee.', answer: 'NOT GIVEN', hints: ['Bài có so sánh nhiệt độ nước giữa 2 loài không?', 'Tìm thông tin nhiệt độ cho từng loài phụ.', 'Có dữ liệu cụ thể để so sánh không?'], explanation: 'NOT GIVEN — Bài nêu Florida manatee tránh nước dưới 20°C, nhưng không so sánh với Antillean.' },
    { id: 9, type: 'tfng', question: 'Q9: The African manatee\'s range is limited to coastal waters between Mauritania and Angola.', answer: 'FALSE', hints: ['Đoạn 7 nói gì về phạm vi sống của African manatee?', 'Tìm "also makes use of rivers"', 'Chúng chỉ sống ở ven biển thôi sao?'], explanation: 'FALSE — <em>"The species also makes use of rivers, with the mammals seen in landlocked countries such as Mali and Niger"</em>.' },
    { id: 10, type: 'tfng', question: 'Q10: The extent of the loss of Amazonian manatees in the mid-20th century was only revealed many years later.', answer: 'NOT GIVEN', hints: ['Bài có nói khi nào thông tin về số lượng bị giết được tiết lộ không?', 'Tìm đoạn về "140,000 Amazonian manatees"', 'Có nêu thời điểm phát hiện thông tin này không?'], explanation: 'NOT GIVEN — Bài nêu con số 140,000 nhưng không nói khi nào thông tin này được tiết lộ.' },
    { id: 11, type: 'tfng', question: 'Q11: It is predicted that West Indian manatee populations will fall in the coming decades.', answer: 'TRUE', hints: ['Tìm dự đoán về số lượng West Indian manatee.', 'Tìm "expected to undergo a decline"', 'Bao nhiêu phần trăm trong bao nhiêu năm?'], explanation: 'TRUE — <em>"Both are also expected to undergo a decline of 20% over the next 40 years"</em>.' },
    { id: 12, type: 'tfng', question: 'Q12: The risk to manatees from entanglement and plastic consumption increased significantly in the period 2009–2020.', answer: 'NOT GIVEN', hints: ['Bài có nói rủi ro TĂNG trong giai đoạn đó không?', 'Tìm đoạn về "1,800 cases"', 'Có so sánh với giai đoạn trước không?'], explanation: 'NOT GIVEN — Bài nêu 1,800 trường hợp trong 2009–2020 nhưng không so sánh với giai đoạn trước.' },
    { id: 13, type: 'tfng', question: 'Q13: There is some legislation in place which aims to reduce boat strikes on manatees in Florida.', answer: 'TRUE', hints: ['Đoạn cuối nói gì về luật ở Florida?', 'Tìm "laws in certain parts of Florida"', 'Luật đó nhằm mục đích gì?'], explanation: 'TRUE — <em>"laws in certain parts of Florida now limit boat speeds during winter, allowing slow-moving manatees more time to respond"</em>.' },
  ]
},

// ══════════════════════════════════════════════════════════════════════════
// TEST 2 — PASSAGE 2: Procrastination
// ══════════════════════════════════════════════════════════════════════════
{
  id: 'cam20-t2-p2',
  title: 'Procrastination',
  topic: 'Psychology',
  band: '6.5 – 7.5',
  difficulty: 'Advanced',
  source: '📗 Cambridge IELTS 20 — Test 2, Passage 2',
  wordCount: 820,
  estimatedTime: 20,
  text: `<strong>A psychologist explains why we put off important tasks and how we can break this habit.</strong>

<strong>A</strong> Procrastination is the habit of delaying a necessary task, usually by focusing on less urgent, more enjoyable, and easier activities instead. We all do it from time to time. We might be composing a message to a friend who we have to let down, or putting together an important report for college or work; we're doing our best to avoid doing the job at hand, but deep down we know that we should just be getting on with it. Unfortunately, berating ourselves won't stop us procrastinating again. In fact, it's one of the worst things we can do. This matters because, as my research shows, procrastination doesn't just waste time, but is actually linked to other problems, too.

<strong>B</strong> Contrary to popular belief, procrastination is not due to laziness or poor time management. Scientific studies suggest procrastination is, in fact, caused by poor mood management. This makes sense if we consider that people are more likely to put off starting or completing tasks that they are really not keen to do. If just thinking about the task threatens our sense of self-worth or makes us anxious, we will be more likely to put it off. Research involving brain imaging has found that areas of the brain linked to detection of threats and emotion regulation are actually different in people who chronically procrastinate compared to those who don't procrastinate frequently.

<strong>C</strong> Tasks that are emotionally loaded or difficult, such as preparing for exams, are prime candidates for procrastination. People with low self-esteem are more likely to procrastinate. Another group of people who tend to procrastinate are perfectionists, who worry their work will be judged harshly by others. We know that if we don't finish that report or complete those home repairs, then what we did can't be evaluated. When we avoid such tasks, we also avoid the negative emotions associated with them. This is rewarding, and it conditions us to use procrastination to repair our mood. If we engage in more enjoyable tasks instead, we get another mood boost. In the long run, however, procrastination isn't an effective way of managing emotions. The 'mood repair' we experience is temporary. Afterwards, people tend to be left with a sense of guilt that not only increases their negative mood, but also reinforces their tendency to procrastinate.

<strong>D</strong> So why is this such a problem? When most people think of the costs of procrastination, they think of the toll on productivity. For example, studies have shown that procrastination negatively impacts on student performance. But putting off reading textbooks and writing essays may affect other areas of students' lives. In one study of over 3,000 German students over a six-month period, those who reported procrastinating over their university work were also more likely to engage in study-related misconduct, such as cheating and plagiarism. But the behaviour that procrastination was most closely linked with was using fraudulent excuses to get deadline extensions. Other research shows that employees on average spend almost a quarter of their workday procrastinating, and again this is linked with negative outcomes. In fact, in one US survey of over 22,000 employees, participants who said they regularly procrastinated had less annual income and less employment stability. For every one-point increase on a measure of chronic procrastination, annual income decreased by US$15,000.

<strong>E</strong> Procrastination also correlates with serious health and well-being problems. A tendency to procrastinate is linked to poor mental health, including higher levels of depression and anxiety. Across numerous studies, I've found people who regularly procrastinate report a greater number of health issues, such as headaches, flu and colds, and digestive issues. They also experience higher levels of stress and poor sleep quality. They are less likely to practise healthy behaviours, such as eating a healthy diet and regularly exercising, and use destructive coping strategies to manage their stress. In one study of over 700 people, I found people prone to procrastination had a 63% greater risk of poor heart health after accounting for other personality traits and demographics.

<strong>F</strong> Finding better ways of managing our emotions is one route out of the vicious cycle of procrastination. An important first step is to manage our environment and how we view the task. There are a number of evidence-based strategies that can help us fend off distractions. For example, reminding ourselves about why the task is important and valuable can increase positive feelings towards it. Forgiving ourselves and feeling compassion when we procrastinate can help break the procrastination cycle. We should admit that we feel bad, but not be overly critical of ourselves. We should remind ourselves that we're not the first person to procrastinate, nor the last. Doing this can take the edge off the negative feelings we have about ourselves when we procrastinate. This can all make it easier to get back on track.`,
  questions: [
    { id: 1, type: 'mc', question: 'Q14: Which paragraph mentions false assumptions about why people procrastinate?', options: ['A. Paragraph A', 'B. Paragraph B', 'C. Paragraph C', 'D. Paragraph D'], answer: 'B', hints: ['Tìm đoạn phản bác niềm tin phổ biến.', 'Tìm "Contrary to popular belief"', 'Đoạn nào nói procrastination KHÔNG phải do lười?'], explanation: 'B — <em>"Contrary to popular belief, procrastination is not due to laziness or poor time management"</em>.' },
    { id: 2, type: 'mc', question: 'Q15: Which paragraph references the realisation that others also procrastinate?', options: ['A. Paragraph C', 'B. Paragraph D', 'C. Paragraph E', 'D. Paragraph F'], answer: 'D', hints: ['Tìm đoạn khuyên nhắc rằng mình không đơn độc.', 'Tìm "not the first person to procrastinate"', 'Đoạn nào nói về "forgiving ourselves"?'], explanation: 'D — Paragraph F: <em>"We should remind ourselves that we\'\'re not the first person to procrastinate, nor the last"</em>.' },
    { id: 3, type: 'mc', question: 'Q16: Which paragraph provides neurological evidence of a link between procrastination and emotion?', options: ['A. Paragraph A', 'B. Paragraph B', 'C. Paragraph C', 'D. Paragraph E'], answer: 'B', hints: ['Tìm đoạn đề cập đến brain imaging.', 'Tìm "brain linked to detection of threats"', 'Bằng chứng thần kinh ở đoạn nào?'], explanation: 'B — <em>"Research involving brain imaging has found that areas of the brain linked to detection of threats and emotion regulation are actually different"</em>.' },
    { id: 4, type: 'short', question: 'Q17: Many people think procrastination is the result of (17) ___________.', answer: 'laziness', hints: ['Đoạn B, câu đầu tiên.', 'Tìm "not due to…"', 'Mọi người nghĩ sai điều gì?'], explanation: 'laziness — <em>"procrastination is not due to <strong>laziness</strong> or poor time management"</em>.' },
    { id: 5, type: 'short', question: 'Q18: Tasks that could damage self-esteem or cause us to feel (18) ___________ are likely to be put off.', answer: 'anxious', hints: ['Đoạn B, tìm cảm giác khi nghĩ đến nhiệm vụ.', 'Tìm "threatens our sense of self-worth or makes us…"', 'Ngoài tự ti, cảm giác gì nữa?'], explanation: 'anxious — <em>"threatens our sense of self-worth or makes us <strong>anxious</strong>"</em>.' },
    { id: 6, type: 'short', question: 'Q19: Research found differences in brain regions associated with regulating emotions and identifying (19) ___________.', answer: 'threats', hints: ['Đoạn B, phần brain imaging.', 'Tìm "detection of…"', 'Não phát hiện gì?'], explanation: 'threats — <em>"areas of the brain linked to detection of <strong>threats</strong> and emotion regulation"</em>.' },
    { id: 7, type: 'short', question: 'Q20: Getting ready to take (20) ___________ might be a typical example of a difficult task.', answer: 'exams', hints: ['Đoạn C, ví dụ về nhiệm vụ khó.', 'Tìm "preparing for…"', 'Chuẩn bị cho cái gì?'], explanation: 'exams — <em>"Tasks that are emotionally loaded or difficult, such as preparing for <strong>exams</strong>"</em>.' },
    { id: 8, type: 'short', question: 'Q21: People likely to procrastinate tend to be either (21) ___________ or those with low self-esteem.', answer: 'perfectionists', hints: ['Đoạn C, 2 nhóm người hay trì hoãn.', 'Tìm "Another group of people"', 'Nhóm nào lo bị đánh giá khắt khe?'], explanation: 'perfectionists — <em>"Another group of people who tend to procrastinate are <strong>perfectionists</strong>"</em>.' },
    { id: 9, type: 'short', question: 'Q22: Procrastination is followed by a feeling of (22) ___________, which worsens mood.', answer: 'guilt', hints: ['Đoạn C, cuối đoạn.', 'Tìm "a sense of…"', 'Cảm giác gì sau khi trì hoãn?'], explanation: 'guilt — <em>"people tend to be left with a sense of <strong>guilt</strong>"</em>.' },
    { id: 10, type: 'mc', question: 'Q23–24: Which TWO comparisons between procrastinating employees and others are mentioned? (Pick first)', options: ['A. Their salaries are lower.', 'B. The quality of their work is inferior.', 'C. They do not keep their jobs for as long.', 'D. They do not enjoy their working lives as much.'], answer: 'A', hints: ['Đoạn D, phần nói về nhân viên.', 'Tìm "less annual income"', 'So sánh thu nhập?'], explanation: 'A — <em>"participants who said they regularly procrastinated had <strong>less annual income</strong>"</em>.' },
    { id: 11, type: 'mc', question: 'Q23–24: Which is the SECOND comparison? (employment stability)', options: ['A. Their salaries are lower.', 'B. The quality of their work is inferior.', 'C. They do not keep their jobs for as long.', 'D. They do not enjoy their working lives as much.'], answer: 'C', hints: ['Tìm thêm "less employment stability"', 'Ổn định công việc kém = không giữ việc lâu?', 'Đáp án nào phù hợp?'], explanation: 'C — <em>"less employment stability"</em> = they do not keep their jobs for as long.' },
    { id: 12, type: 'mc', question: 'Q25–26: Which recommendation for breaking procrastination does the writer give? (first)', options: ['A. not judging ourselves harshly', 'B. setting ourselves manageable aims', 'C. rewarding ourselves for tasks achieved', 'D. prioritising tasks according to importance', 'E. avoiding distractions'], answer: 'A', hints: ['Đoạn F, các chiến lược.', 'Tìm "not be overly critical of ourselves"', 'Đó là lời khuyên nào?'], explanation: 'A — <em>"not be overly critical of ourselves"</em> = not judging ourselves harshly.' },
    { id: 13, type: 'mc', question: 'Q25–26: Which is the second recommendation?', options: ['A. not judging ourselves harshly', 'B. setting manageable aims', 'C. rewarding ourselves', 'D. prioritising tasks', 'E. avoiding things that stop us concentrating'], answer: 'E', hints: ['Tìm thêm lời khuyên trong đoạn F.', 'Tìm "fend off distractions"', 'Tránh xao nhãng?'], explanation: 'E — <em>"a number of evidence-based strategies that can help us fend off distractions"</em>.' },
  ]
},

];

PASSAGES.push(...CAM20_T2);
