// Cambridge IELTS 20 — Test 3 Passages
const CAM20_T3 = [

// ══════════════════════════════════════════════════════════════════════════
// TEST 3 — PASSAGE 1: The history of frozen food
// ══════════════════════════════════════════════════════════════════════════
{
  id: 'cam20-t3-p1',
  title: 'The history of frozen food',
  topic: 'History & Technology',
  band: '6.0 – 7.0',
  difficulty: 'Intermediate',
  source: '📗 Cambridge IELTS 20 — Test 3, Passage 1',
  wordCount: 780,
  estimatedTime: 20,
  text: `<strong>The story of frozen food stretches back at least 2,000 years to South America.</strong> The Quechua people, who lived high up in the Andes mountains, created a substance called chu\u00f1o. This was produced by taking potatoes to the mountain tops and leaving them out to freeze in the cold, thin air. This process of repeated freezing and sun-drying preserved the nutritional value of food and kept it from going bad.

In the early 1800s, Tudor, a businessman from Boston, USA, created a profitable business by cutting ice from frozen lakes in New England and shipping it south in insulated ships. Milk was kept cool by ice during transportation in specially adapted trains. Tudor also exported ice around the world. Ice became such a vital commodity that it changed the way people ate and preserved food.

In 1851, a Scottish-Australian inventor named James Harrison built the first mechanical ice-making machine. He used a compressor to force gas through a condenser, which cooled it to a liquid. This liquid was then passed through an evaporator coil where it absorbed heat and evaporated. Air was blown over the evaporator coil and then this cooled air passed into an insulated compartment, lowering its temperature to freezing point. Initially, this process was invented to keep Australian beer cool even in hot weather. But Australian cattlemen were quick to realize that, if they could put this new invention on a ship, they could export meat across the oceans. In 1880, a shipment of Australian beef and mutton was sent, frozen, to England. While the food frozen this way was still palatable, there was some deterioration. During the freezing process, crystals formed within the cells of the food, and when the ice expanded and the cells burst, this spoilt the flavor and texture of the food.

The modern frozen food industry began with the indigenous Inuit people of Canada. In 1912, a biology student named Clarence Birdseye ran out of money and went to Labrador in Canada to trap and trade furs. While he was there, he became fascinated with how the Inuit would quickly freeze fish in the Arctic air. The fish looked and tasted fresh even months later.

Birdseye returned to the USA in 1917 and began developing mechanical freezers capable of quick-freezing food. He methodically kept inventing better freezers and gradually built a business selling frozen fish. In 1929, his business was sold and became General Foods, but he stayed with the company as director of research. Birdseye was responsible for several key innovations: he developed quick-freezing techniques that reduced the damage that crystals caused, as well as the technique of freezing the product in the package it was to be sold in. He also introduced the use of cellophane, the first transparent material for food packaging, which allowed consumers to see the quality of the product.

But there were still obstacles. In the 1930s, few grocery stores could afford to buy freezers for a market that was not established yet. So, Birdseye leased inexpensive freezer cases to them. He also leased insulated railroad cars so that he could ship his products nationwide. However, few consumers had freezers large enough to take advantage of the products.

Sales increased in the early 1940s, when World War II gave a boost to the frozen food industry because tin was being used for munitions. Canned foods were rationed to save tin for the war effort, while frozen foods were abundant and cheap. Finally, by the 1950s, refrigerator technology had developed far enough to make appliances affordable for the average family. By 1953, 31 million US families owned a refrigerator.

1950s families were also looking for convenience at mealtimes, so the moment was right for the arrival of the TV Dinner. Swanson Foods adapted some of Birdseye's freezing techniques, and with the help of a clever name and a huge advertising budget, launched the first TV Dinner in 1954. Within a year, Swanson had sold 13 million TV dinners. Today, the US frozen food industry has a turnover of over $67 billion annually.`,
  questions: [
    { id: 1, type: 'short', question: 'Q1: 2,000 years ago in South America, people conserved the nutritional value of (1) _______ using a method of freezing then drying.', answer: 'potatoes', hints: ['Đoạn 1 nói về người Quechua.', 'Tìm thực phẩm nào được đem lên đỉnh núi.', 'Chu\u00f1o được làm từ gì?'], explanation: 'potatoes \u2014 <em>"taking <strong>potatoes</strong> to the mountain tops and leaving them out to freeze"</em>.' },
    { id: 2, type: 'short', question: 'Q2: In 1851, (2) _______ was kept cool by ice during transportation in specially adapted trains.', answer: 'milk|Milk', hints: ['Đoạn 2 nói về kinh doanh đá.', 'Tìm thứ được vận chuyển bằng tàu hỏa đặc biệt.', 'Sản phẩm nào cần giữ lạnh khi vận chuyển?'], explanation: 'Milk \u2014 <em>"<strong>Milk</strong> was kept cool by ice during transportation in specially adapted trains"</em>.' },
    { id: 3, type: 'short', question: 'Q3: In 1880, two kinds of (3) _______ were the first frozen food shipped to England.', answer: 'meat', hints: ['Đoạn 3, lô hàng đông lạnh đầu tiên từ Australia.', 'Tìm "beef and mutton"', 'Cả hai đều là loại gì?'], explanation: 'meat \u2014 <em>"a shipment of Australian beef and mutton"</em> = meat.' },
    { id: 4, type: 'short', question: 'Q4: Birdseye introduced quick-freezing methods, so that (4) _______ did not spoil the food.', answer: 'crystals', hints: ['Đoạn 5 nói về cải tiến của Birdseye.', 'Tìm "reduced the damage that... caused"', 'Cái gì gây hư hại khi đông lạnh chậm?'], explanation: 'crystals \u2014 <em>"quick-freezing techniques that reduced the damage that <strong>crystals</strong> caused"</em>.' },
    { id: 5, type: 'short', question: 'Q5: Birdseye packaged products with (5) _______ so the product was visible.', answer: 'cellophane', hints: ['Đoạn 5, vật liệu đóng gói mới.', 'Tìm "first transparent material"', 'Tên vật liệu đó là gì?'], explanation: 'cellophane \u2014 <em>"the use of <strong>cellophane</strong>, the first transparent material for food packaging"</em>.' },
    { id: 6, type: 'short', question: 'Q6: In the early 1940s, frozen food became popular because of a shortage of (6) _______.', answer: 'tin', hints: ['Đoạn 7, ảnh hưởng của WWII.', 'Tìm "tin was being used for munitions"', 'Thiếu gì nên thực phẩm đóng hộp bị hạn chế?'], explanation: 'tin \u2014 <em>"tin was being used for munitions. Canned foods were rationed to save <strong>tin</strong>"</em>.' },
    { id: 7, type: 'short', question: 'Q7: In the 1950s, a large number of homes now had a (7) _______.', answer: 'refrigerator', hints: ['Đoạn 7, cuối đoạn.', 'Tìm "31 million US families owned a..."', 'Thiết bị gia đình phổ biến là gì?'], explanation: 'refrigerator \u2014 <em>"31 million US families owned a <strong>refrigerator</strong>"</em>.' },
    { id: 8, type: 'tfng', question: 'Q8: The ice transportation business made some Boston ship owners very wealthy in the early 1800s.', answer: 'NOT GIVEN', hints: ['Bài có nói ai trở nên giàu có không?', 'Tìm thông tin về Tudor ở Boston.', 'Có đề cập đến "wealthy" hoặc tương đương không?'], explanation: 'NOT GIVEN \u2014 Bài nêu Tudor có kinh doanh có lãi ("profitable") nhưng không nói về ship owners trở nên giàu có.' },
    { id: 9, type: 'tfng', question: 'Q9: A disadvantage of the freezing process invented in Australia was that it affected the taste of food.', answer: 'TRUE', hints: ['Đoạn 3, nhược điểm của đông lạnh cơ khí.', 'Tìm "spoilt the flavor and texture"', 'Vị bị ảnh hưởng không?'], explanation: 'TRUE \u2014 <em>"this spoilt the flavor and texture of the food"</em>.' },
    { id: 10, type: 'tfng', question: 'Q10: Clarence Birdseye travelled to Labrador in order to learn how the Inuit people froze fish.', answer: 'FALSE', hints: ['Tại sao Birdseye đến Labrador?', 'Tìm "ran out of money"', 'Anh ấy đi với mục đích gì?'], explanation: 'FALSE \u2014 Anh ấy đến để "trap and trade furs" (bẫy thú và buôn lông), không phải để học cách đông lạnh cá.' },
    { id: 11, type: 'tfng', question: 'Q11: Swanson Foods invested a great deal of money in the promotion of the TV Dinner.', answer: 'TRUE', hints: ['Đoạn 8 nói gì về quảng cáo của Swanson?', 'Tìm "advertising budget"', 'Ngân sách quảng cáo lớn hay nhỏ?'], explanation: 'TRUE \u2014 <em>"a huge advertising budget"</em>.' },
    { id: 12, type: 'tfng', question: 'Q12: Swanson Foods developed a new style of container for the launch of the TV Dinner.', answer: 'FALSE', hints: ['Đoạn 8, loại khay nào được sử dụng?', 'Tìm "segmented aluminum tray"', 'Khay đó có phải Swanson phát minh không?'], explanation: 'FALSE \u2014 <em>"the same segmented aluminum tray that was used by airlines"</em> \u2014 khay cũ từ hàng không, không phải phát minh mới.' },
    { id: 13, type: 'tfng', question: 'Q13: The US frozen food industry is currently the largest in the world.', answer: 'NOT GIVEN', hints: ['Bài có so sánh Mỹ với các nước khác không?', 'Tìm đoạn cuối về doanh thu.', 'Có nói "largest in the world" không?'], explanation: 'NOT GIVEN \u2014 Bài nêu doanh thu $67 tỷ nhưng không so sánh với quốc gia nào khác.' },
  ]
},

// ══════════════════════════════════════════════════════════════════════════
// TEST 3 — PASSAGE 2: Can the planet's coral reefs be saved?
// ══════════════════════════════════════════════════════════════════════════
{
  id: 'cam20-t3-p2',
  title: 'Can the planet\u2019s coral reefs be saved?',
  topic: 'Environment & Conservation',
  band: '6.5 – 7.5',
  difficulty: 'Advanced',
  source: '📗 Cambridge IELTS 20 — Test 3, Passage 2',
  wordCount: 750,
  estimatedTime: 20,
  text: `<strong>A</strong> Conservationists have put the final touches to a giant artificial reef at London Zoo. Samples of the planet's most spectacular corals have been added to the giant tank along with fish. The reef is in the zoo's new gallery, Tiny Giants, which is dedicated to minuscule invertebrate creatures. Paul Pearce-Kelly, senior curator, said: 'Coral reefs are the most diverse ecosystems on Earth and we want to show people how wonderful they are. However, we also want to highlight the research and conservation efforts being carried out to save them from the threat of global warming.'

<strong>B</strong> Corals are composed of tiny animals, known as polyps, with tentacles for capturing small marine creatures. These polyps are transparent but get their brilliant tones from algae that live within them, which in turn get protection, while their photosynthesising provides nutrients for the polyps. This symbiotic relationship has led to the growth of coral reefs that cover 0.1% of the ocean bed while providing homes for more than 25% of marine species.

<strong>C</strong> Coral reefs are often described as the 'rainforests of the sea', though the comparison is dismissed by some naturalists, including David Attenborough: 'People say you cannot beat the rainforest. But that is simply not true. You go there and the first thing you think is: where are the birds? Where are the animals? They are hidden. But on a reef everything is out in the open.'

<strong>D</strong> This is worrying because as climate change progresses, the future for coral reefs looks extremely bleak. Increasing sea temperatures cause a phenomenon known as coral bleaching, which strips the colour from coral by expelling the algae that give the creatures their vibrant hues. In addition, overfishing, pollution and changes in ocean currents are degrading reefs.

<strong>E</strong> Researchers at London Zoo are working to identify corals that are most resilient to changing sea conditions and to develop techniques to breed these. Additionally, researchers are exploring methods to speed up reproduction. Studies carried out at one centre can then be tested at others.

<strong>F</strong> Research in these fields is being conducted in laboratories around the world, with the London Zoo centre linked to this global network. The resulting young coral can then be displayed in the tank in Tiny Giants. 'The crucial point is that the progress we make in making coral better able to survive in a warming world can be shown to the public and encourage them to believe that we can do something to save the planet's reefs,' said Pearce-Kelly.`,
  questions: [
    { id: 1, type: 'mc', question: 'Q14: Which heading fits Section A?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement about a certain phrase', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning of further trouble ahead'], answer: 'E', hints: ['Đoạn A nêu mục đích gì?', 'Tìm 2 mục tiêu: "show people how wonderful" và "highlight research"', '2 mục tiêu giáo dục?'], explanation: 'v \u2014 Two clear educational goals: show how wonderful + highlight conservation efforts.' },
    { id: 2, type: 'mc', question: 'Q15: Which heading fits Section B?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement about a certain phrase', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning of further trouble ahead'], answer: 'B', hints: ['Đoạn B nói về mối quan hệ giữa polyps và algae.', 'Đó là sự cộng sinh = hợp tác?', 'Cooperation dưới nước?'], explanation: 'ii \u2014 Cooperation beneath the waves: symbiotic relationship between polyps and algae.' },
    { id: 3, type: 'mc', question: 'Q16: Which heading fits Section C?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement about accuracy of a certain phrase', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning of further trouble ahead'], answer: 'D', hints: ['Đoạn C thảo luận "rainforests of the sea".', 'Attenborough không đồng ý so sánh đó.', 'Đó là bất đồng về một cụm từ?'], explanation: 'iv \u2014 Disagreement about the accuracy of a certain phrase: Attenborough dismisses the comparison.' },
    { id: 4, type: 'mc', question: 'Q17: Which heading fits Section D?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement about accuracy of a certain phrase', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning of further trouble ahead'], answer: 'G', hints: ['Đoạn D nói về tương lai ảm đạm.', 'Tìm "the future looks extremely bleak"', 'Cảnh báo về rắc rối sắp tới?'], explanation: 'vii \u2014 A warning of further trouble ahead: bleaching, overfishing, pollution.' },
    { id: 5, type: 'mc', question: 'Q18: Which heading fits Section E?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning'], answer: 'C', hints: ['Đoạn E nói về nghiên cứu nhằm giảm thiểu vấn đề.', 'Tìm "identify corals that are most resilient"', 'Đang làm việc để giảm bớt vấn đề?'], explanation: 'iii \u2014 Working to lessen the problems: identifying resilient corals and breeding.' },
    { id: 6, type: 'mc', question: 'Q19: Which heading fits Section F?', options: ['i. Tried and tested solutions', 'ii. Cooperation beneath the waves', 'iii. Working to lessen the problems', 'iv. Disagreement', 'v. Two clear educational goals', 'vi. Promoting hope', 'vii. A warning'], answer: 'F', hints: ['Đoạn F nói về hy vọng.', 'Tìm "encourage them to believe we can do something"', 'Khuyến khích niềm tin = quảng bá hy vọng?'], explanation: 'vi \u2014 Promoting hope: encouraging the public to believe reefs can be saved.' },
    { id: 7, type: 'mc', question: 'Q20-21: Which TWO causes of damage to coral reefs are mentioned? (first)', options: ['A. a rising number of extreme storms', 'B. the removal of too many fish', 'C. contamination of the sea from waste', 'D. increased disease among marine species', 'E. alterations in the usual flow of water'], answer: 'B', hints: ['Đoạn D liệt kê nguyên nhân.', 'Tìm "overfishing"', 'Đánh bắt quá mức = lấy quá nhiều cá?'], explanation: 'B \u2014 <em>"overfishing"</em> = removal of too many fish.' },
    { id: 8, type: 'mc', question: 'Q20-21: Second cause mentioned?', options: ['A. extreme storms', 'B. too many fish removed', 'C. contamination from waste', 'D. increased disease', 'E. alterations in water flow'], answer: 'E', hints: ['Tìm thêm nguyên nhân trong đoạn D.', 'Tìm "changes in ocean currents"', 'Thay \u0111\u1ed5i d\u00f2ng ch\u1ea3y?'], explanation: 'E \u2014 <em>"changes in ocean currents"</em> = alterations in the usual flow of water.' },
    { id: 9, type: 'mc', question: 'Q22-23: Which TWO statements about London Zoo researchers are true? (first)', options: ['A. Expand numbers of different corals bred', 'B. Identify corals that cope well with changed conditions', 'C. Create artificial reefs for corals', 'D. Speed up reproduction in some corals', 'E. Investigate materials to protect from heat'], answer: 'B', hints: ['Đoạn E nói gì về mục tiêu nghiên cứu?', 'Tìm "identify corals that are most resilient"', 'T\u00ecm san h\u00f4 ch\u1ecbu \u0111\u01b0\u1ee3c nhi\u1ec7t?'], explanation: 'B \u2014 <em>"identify corals that are most resilient to changing sea conditions"</em>.' },
    { id: 10, type: 'mc', question: 'Q22-23: Second true statement?', options: ['A. Expand breeding', 'B. Identify resilient corals', 'C. Create artificial reefs', 'D. Speed up reproduction', 'E. Investigate protective materials'], answer: 'D', hints: ['Tìm mục tiêu thứ hai của nghiên cứu.', 'Tìm "speed up reproduction"', 'T\u0103ng t\u1ed1c sinh s\u1ea3n?'], explanation: 'D \u2014 <em>"exploring methods to speed up reproduction"</em>.' },
    { id: 11, type: 'short', question: 'Q24: Corals have a number of (24) _______ which they use to collect their food.', answer: 'tentacles', hints: ['Đoạn B, cấu tạo san hô.', 'Tìm "polyps, with... for capturing"', 'Bộ phận nào bắt mồi?'], explanation: 'tentacles \u2014 <em>"polyps, with <strong>tentacles</strong> for capturing small marine creatures"</em>.' },
    { id: 12, type: 'short', question: 'Q25: Algae gain (25) _______ from being inside the coral.', answer: 'protection', hints: ['Đoạn B, mối quan hệ cộng sinh.', 'Tìm "which in turn get..."', 'Tảo được gì từ san hô?'], explanation: 'protection \u2014 <em>"algae that live within them, which in turn get <strong>protection</strong>"</em>.' },
    { id: 13, type: 'short', question: 'Q26: Increases in warmth of sea water can remove the (26) _______ from coral.', answer: 'colour|color', hints: ['Đoạn D, hiện tượng coral bleaching.', 'Tìm "strips the... from coral"', 'Tẩy trắng san hô = mất gì?'], explanation: 'colour \u2014 <em>"coral bleaching, which strips the <strong>colour</strong> from coral"</em>.' },
  ]
},

];

PASSAGES.push(...CAM20_T3);
